server:
  port: 8081

spring:
  profiles:
    active: dev

spring.datasource:
  url: jdbc:mysql://8.140.128.40:3306/seata_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: ENC(sayBcmf2PyWdcvEaLrVpZw==)
  password: ENC(cmD0rRscCYEMiViTSmnRNJu9gy9UsAOm)
  driver-class-name: com.mysql.cj.jdbc.Driver
  continue-on-error: true
  sql-script-encoding: UTF-8
