
server:
  port: 8080

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        prfix: xiaozao
        file-exetension: yml
      discovery:
        server-addr: 127.0.0.1:8848

