
server:
  port: 8080

# nacos 配置
spring.cloud:
  nacos:
    config:
      server-addr: 127.0.0.1:8848
      fileExtension: yaml
      extConfig:
        - dataid: maple.yaml
          group: DEFAULT_GROUP
          refresh: true
        - dataid: maple-account.yaml
          group: DEFAULT_GROUP
          refresh: true
    discovery:
      server-addr: 127.0.0.1:8848
      namespace: dev
